### ISSUE TITLE
When will python version provided?

### ISSUE THREAD

**Issue by isaac7778** [MasterMilkX/KekeCompetition#3]
Hello, I want to participate in the competition, but I am not familiar with JS. So I am waiting for the python version. 
When it will be uploaded?

**Comment by MasterMilkX** [comment]
Hi,

We plan to include the Python framework in next year's competition, sorry. We were pressed for time to submit the competition to the CoG conference, and didn't have time to port the engine. As a regular Python and JS user, I can assure you the languages are very similar and the learning curve is minimal :)

Thanks!
